name: Build GalaxyTimer (PyInstaller only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 90
    env:
      PYTHON_VERSION: '3.10'
      ENTRY: pyscript/galaxytimer.py

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip & install build tools
        shell: pwsh
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pyinstaller pyttsx3

      - name: Install requirements if present
        shell: pwsh
        run: |
          if (Test-Path requirements.txt) {
            python -m pip install -r requirements.txt
          } else {
            Write-Host "no requirements.txt"
          }

      - name: Inject build salt (optional)
        shell: pwsh
        run: |
          # Generate random salt
          $bytes = New-Object byte[] 12
          $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
          $rng.GetBytes($bytes)
          $salt = [System.Convert]::ToBase64String($bytes) -replace '/','_' -replace '\+','-' -replace '=',''
          if ($salt.Length -gt 16) { $salt = $salt.Substring(0,16) }
          Write-Host "Generated SALT: $salt"
          Add-Content -Path $env:GITHUB_ENV -Value "BUILD_SALT=$salt"

          # Inject into file
          $entryPath = Join-Path -Path (Get-Location) -ChildPath $env:ENTRY
          (Get-Content $entryPath -Raw) -replace "__BUILD_SALT__", $salt | Set-Content $entryPath -Encoding UTF8

      - name: Check Encoding of Entry File
        shell: pwsh
        run: |
          $entryPath = Join-Path -Path (Get-Location) -ChildPath $env:ENTRY
          if (Get-Content $entryPath -Raw | Out-Null) {
              Write-Host "Entry file encoding check passed."
          } else {
              Write-Error "Unable to read entry file. Please check encoding."
              exit 1
          }

      - name: Build with PyInstaller
        shell: pwsh
        run: |
          $iconPath = ".\resources\icon\icon.ico"  # 确保路径的正确性
          if (-not (Test-Path $iconPath)) {
            Write-Host "Icon not found, continuing without setting an icon."
            pyinstaller --noconfirm --onefile --hidden-import=pyttsx3 $env:ENTRY
          } else {
            pyinstaller --noconfirm --onefile --hidden-import=pyttsx3 --icon=$iconPath $env:ENTRY
          }

      - name: Rename and publish exe (move dist\galaxytimer.exe -> GalaxyTimer.exe)
        shell: pwsh
        run: |
          $exePath = Join-Path -Path (Get-Location) -ChildPath "dist\galaxytimer.exe"
          if (Test-Path $exePath) {
            Move-Item -Force $exePath .\GalaxyTimer.exe
            Write-Host "Moved to GalaxyTimer.exe"
          } else {
            Write-Error "GalaxyTimer.exe not found in the dist directory."
          }

      - name: Clean intermediate files (optional)
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force -ErrorAction SilentlyContinue .\dist, .\build
          Get-ChildItem -Path . -Filter "*.spec" -File | ForEach-Object { Remove-Item -Force $_.FullName }

      - name: Upload GalaxyTimer.exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: GalaxyTimer-exe
          path: GalaxyTimer.exe
